### ISSUE TITLE
[BUG] lark.exceptions.UnexpectedCharacters

### ISSUE THREAD

**Issue by elvizlai** [bufbuild/protovalidate-python#229]
## Description

Followed by https://github.com/bufbuild/protovalidate-python?tab=readme-ov-file#usage instruction, but failed 

```
    raise UnexpectedCharacters(lex_state.text, line_ctr.char_pos, line_ctr.line, line_ctr.column,
lark.exceptions.UnexpectedCharacters: No terminal matches 'o' in the current parser context, at line 1 col 23

(this.startswith('$') or this.startswith('£')) and float(this[
                      ^
Expected one of:
	* "!="
	* "=="
	* COLON
	* PLUS
	* ">="
	* COMMA
	* "||"
	* RSQB
	* QMARK
	* "<="
	* MORETHAN
	* MINUS
	* IN
	* LESSTHAN
	* RPAR
	* STAR
	* LBRACE
	* RBRACE
	* SLASH
	* DOT
	* PERCENT
	* "&&"
	* LSQB

Previous tokens: Token('RPAR', ')')
```

## Environment

- **Operating System**: 
- **Version**: 
- **Compiler/Toolchain**: 
- **Protobuf Compiler & Version**: 
- **Protoc-gen-validate Version**: 
- **Protovalidate Version**:

**Comment by stefanvanburen** [comment]
Hi @elvizlai, looks like that was just some invalid CEL — have a fix in https://github.com/bufbuild/protovalidate-python/pull/230.
