### ISSUE TITLE
[Question] How to install?

### ISSUE THREAD

**Issue by colinmiller94** [bufbuild/protovalidate-python#48]
Per the readme: I've done: 
`pip install protovalidate`

And created the example .proto (and named it transaction.proto)
Then try `protoc --python_out=. transaction.proto `

Unsurprisingly: 
```
buf/validate/validate.proto: File not found.
transaction.proto:6:1: Import "buf/validate/validate.proto" was not found or had errors.
```

Seems like the .proto it's looking for is in the [main repo](https://github.com/bufbuild/protovalidate), but I've been stuck to trying to get the import to work.

**Comment by elliotmjackson** [comment]
resolved in https://github.com/bufbuild/protovalidate-python/pull/54
