### ISSUE TITLE
support proto-plus wrapped types

### ISSUE THREAD

**Issue by tmc** [bufbuild/protovalidate-python#70]
Does this library support proto-plus defined messages?

https://proto-plus-python.readthedocs.io/en/latest/reference/message.html

If not, please do so. Proto-plus classes have a .pb() method that returns the descriptor.

**Comment by Alfus** [comment]
pb() needs the obj argument: "obj – If provided, and an instance of cls, return the underlying protobuf instance."
Once you have the actual protobuf instance, it can be passed directly to the protovalidate library.
